In [3]:
import numpy as np

In [12]:
np.zeros((3,2))
np.ones((5))
np.full((5,4), 3) #np.threes()
np.identity(4)

#First way to create an array from Shape/Values

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
a_list = [[0, 0, 0.5], [1,1,1]]
np.array(a_list)

#Second way to create a array from existing list

array([[0. , 0. , 0.5],
       [1. , 1. , 1. ]])

In [20]:
import numpy.char as char

In [29]:
np.arange(0,10,1)
np.linspace(0,10,4) #it will generate 4 evenly spaced numbers from 0 to 10 (including both endpoints).
#This is third way to create an array from numerical range

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [33]:
np.random.randint(0, 10, (3,3))

array([[3, 2, 2],
       [7, 9, 8],
       [6, 1, 4]])

In [34]:
np.random.rand(3, 3, 2)

array([[[0.89545136, 0.4598023 ],
        [0.5803419 , 0.64437288],
        [0.46717072, 0.47974676]],

       [[0.84301046, 0.48649996],
        [0.23553032, 0.99141887],
        [0.45942448, 0.70165632]],

       [[0.83930488, 0.85836253],
        [0.79012015, 0.38495704],
        [0.84556979, 0.3841496 ]]])

In [35]:
np.random.randn(3, 3)

array([[-2.27036528,  1.20700725, -0.67684329],
       [ 2.07015416, -0.61003628,  0.59695259],
       [-0.26568365, -0.05117282, -0.1908995 ]])

In [36]:
vector = np.array([[0, 1, 2, 3],
                   [4, 5, 6, 5]])


In [37]:
vector.shape 

(2, 4)

In [38]:
vector = np.array([[0, 1, 2, 3], # 3 Rows, 4 Columns
                   [4, 5, 6, 7],
                   [8, 9, 10, 11],])

In [39]:
vector.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [42]:
np.ravel(vector) #np.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
np.reshape(vector, (3,2,-1))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])